apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/konflux-ci/konflux-ci/operator/config/default?ref=318d2d33069275dc770ab44274fe5e8142902ed8
  - konflux.yaml

images:
  - name: localhost/konflux-operator
    newName: quay.io/oamsalem/test
    newTag: 318d2d33069275dc770ab44274fe5e8142902ed8
